name: Release Workflow

on:
  release:
    types: [published]  
  
permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout master branch
        uses: actions/checkout@v3
        with:
          ref: main

      - name: Configure git
        run: |
          git config --global user.email "github-actions@github.com"
          git config --global user.name "GitHub Actions"

      - name: Create a tag from release
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          TAG_NAME="${{ github.event.release.tag_name }}"  # Extracts the tag name from the release event
          echo "Tagging with $TAG_NAME"
          
          # Create and push the tag
          git tag "$TAG_NAME"
          git push origin "$TAG_NAME"          

      - name: Set Node.js 20.x
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: 'yarn'
    
      - name: Check npm version
        run: 
          npm --version
          yarn --version
  
      - name: Confirm current directory
        run: pwd

      - name: List files
        run: ls -la  

      - name: Merge develop into main
        run: |
          git merge --no-ff develop   # need to be updated to development after test
          git push origin
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}


      - name: Bump version
        run: |
          yarn version --new-version "$TAG_NAME"
          # cd apps/api
          # yarn version --new-version "$TAG_NAME"
          # pwd
          # cd ../..
          # cd apps/app
          # yarn version --new-version "$TAG_NAME"

      - name: Commit changes
        run: |
          git add .
          git commit -m "chore: release "$TAG_NAME"
          git push origin main --follow-tags
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
 
